### ISSUE TITLE
Highlight {{tokens}}

### ISSUE THREAD

**Issue by waldyrious** [leostera/tldr.js#6]
Per https://github.com/tldr-pages/tldr/issues/261#issuecomment-76662747

**Comment by waldyrious** [comment]
I don't see this on the live version. Do I need to clear my cache or something?

**Comment by leostera** [comment]
Hey @waldyrious I closed this as this repo is unmaintained altogether. PR's are welcome on tldr.jsx if you're still interested in getting this one done.

**Comment by waldyrious** [comment]
Ah, got you. It would have been better to inform of the reason for closing, then. Thanks for clarifying.
